# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rec',
            old_name='create_time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='rec',
            old_name='user_ip',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='rec',
            old_name='prize_name',
            new_name='prizeName',
        ),
        migrations.RenameField(
            model_name='rec',
            old_name='send_time',
            new_name='sendTime',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='way',
        ),
        migrations.AddField(
            model_name='rec',
            name='isSend',
            field=models.IntegerField(choices=[(0, '未派送'), (1, '已派送')], default=0, verbose_name='是否发送'),
        ),
        migrations.AddField(
            model_name='rec',
            name='prizeId',
            field=models.IntegerField(default=None, verbose_name='奖品ID'),
        ),
        migrations.AddField(
            model_name='rec',
            name='type',
            field=models.IntegerField(choices=[(0, '自然抽奖'), (1, '内定抽奖'), (2, '后台添加')], default=0, verbose_name='抽奖方式'),
        ),
    ]
