# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteadmin',
            name='role',
        ),
    ]
