# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='group',
            field=models.IntegerField(verbose_name='分类'),
        ),
    ]
