# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190316_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='code',
            field=models.IntegerField(default=None, verbose_name='礼品编号'),
        ),
    ]
