# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190316_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='group',
            new_name='grade',
        ),
    ]
