# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190316_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='grade',
            field=models.CharField(max_length=32, verbose_name='分类'),
        ),
    ]
