# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190316_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(default='默认', max_length=32, verbose_name='类别'),
        ),
    ]
