# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190318_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='sequence',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='顺序'),
        ),
    ]
