# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190320_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='censor',
            field=models.CharField(max_length=32, null=True, verbose_name='派送人'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='isSend',
            field=models.IntegerField(choices=[(0, '未派送'), (1, '已派送'), (2, '锁定')], default=0, verbose_name='是否发送'),
        ),
    ]
