# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='活动名称')),
                ('is_open', models.BooleanField(default=False, verbose_name='是否开启')),
                ('errmsg', models.CharField(max_length=100, verbose_name='关闭提示')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=None, unique=True, verbose_name='礼品编号')),
                ('prize_name', models.CharField(max_length=64, verbose_name='礼品名称')),
                ('probability', models.IntegerField(default=0, verbose_name='中奖概率')),
            ],
            options={
                'verbose_name': '奖品管理',
                'verbose_name_plural': '奖品管理',
            },
        ),
    ]
