# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': '活动用户', 'verbose_name_plural': '活动用户'},
        ),
        migrations.AddField(
            model_name='rule',
            name='score',
            field=models.IntegerField(default=0, verbose_name='活动次数'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='sequence',
            field=models.CharField(default='', max_length=64, verbose_name='顺序'),
        ),
    ]
