# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190226_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='end_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='errmsg',
            field=models.CharField(default='活动还未开启', max_length=100, verbose_name='关闭提示'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(default='请设置活动名称', max_length=32, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='info',
            name='start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='开始时间'),
        ),
    ]
